Sat Aug 17 01:08:24, Warn:  Output directory does not exist yet. We therefore create it now. 
[0m[31m(   4.201s) [paraview        ]     vtkCSVExporter.cxx:140    ERR| vtkCSVExporter (0xad04d80): Failed to open for writing: /values-over-line.csv[0m
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/plot_initial_stress_profile.py", line 58, in <module>
    data = pd.read_csv(csvfile)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'values-over-line.csv'
cp: cannot stat '*.err': No such file or directory
cp: cannot stat '*.out': No such file or directory
