Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
terminate called after throwing an instance of 'std::runtime_error'
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
  what():  Error while parsing easi model file.
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
  what():  Error while parsing easi model file.
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
terminate called after throwing an instance of 'std::runtime_error'
Haiti_sig_zz.yaml: yaml-cpp: error at line 1, column 1: unknown token
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
  what():  Error while parsing easi model file.
srun: error: i02r02c06s03: task 3: Aborted (core dumped)
srun: launch/slurm: _step_signal: Terminating StepId=3513267.0
srun: error: i02r03c01s02: task 14: Aborted (core dumped)
srun: error: i02r02c05s12: task 0: Aborted (core dumped)
srun: error: i02r02c06s07: task 7: Aborted (core dumped)
srun: error: i02r02c06s12: task 12: Aborted (core dumped)
srun: error: i02r02c06s10: task 10: Aborted (core dumped)
srun: error: i02r02c06s08: task 8: Aborted (core dumped)
srun: error: i02r02c06s09: task 9: Aborted (core dumped)
srun: error: i02r02c06s05: task 5: Aborted (core dumped)
srun: error: i02r02c06s11: task 11: Aborted (core dumped)
srun: error: i02r03c01s01: task 13: Aborted (core dumped)
srun: error: i02r02c06s06: task 6: Aborted (core dumped)
srun: error: i02r02c06s04: task 4: Aborted (core dumped)
srun: error: i02r02c06s02: task 2: Aborted (core dumped)
srun: error: i02r02c06s01: task 1: Aborted (core dumped)
srun: error: i02r03c01s04: task 15: Aborted (core dumped)
/var/spool/slurm/job3513267/slurm_script: line 66: pushd: /hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/outputs_tmp: No such file or directory
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-fault.xdmf'
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-surface.xdmf'
/var/spool/slurm/job3513267/slurm_script: line 72: popd: directory stack empty
mv: cannot stat '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/outputs_tmp': No such file or directory
cp: cannot create directory '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/regional-only-simplified/jobid_3513267/logs': No such file or directory
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_R_supermuc.py", line 211, in <module>
    generateRMoment(jobid_list)
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_R_supermuc.py", line 87, in generateRMoment
    xdmfFilename, momentCsvFile = find_xdmffile_wahweap(jobid)
  File "/dss/dsshome1/01/di35poq/soft/calc-moment-rate_R_supermuc.py", line 37, in find_xdmffile_wahweap
    momentCsvFile = glob.glob(datadir + '*/jobid_'+jobid+'*/output-energy.csv')[0]
IndexError: list index out of range
